version: '2'
services:
    haproxy:
        image: bylek/cron-haproxy
        ports:
            - "80:80"
        links:
            - frontend
            - backend
        depends_on:
            - mysql
            - backend
            - frontend
    mysql:
        image: bylek/cron-mysql
        environment:
            - MYSQL_ROOT_PASSWORD=root
    backend:
        image: bylek/cron-backend
        restart: always
        links:
            - mysql
        depends_on:
            - mysql
    frontend:
        image: bylek/cron-frontend
        depends_on:
            - backend